name: analyze and test compiler

on:
  push:
    branches: [main]
    paths-ignore:
      - '**/*.md'
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: packages/vector_graphics_compiler
    steps:
    - uses: actions/checkout@v3
    - uses: subosito/flutter-action@v2
      with:
        channel: 'master'
    - run: flutter --version
    - run: flutter pub get
    - run: dart format --set-exit-if-changed .
    - run: flutter analyze .
    - run: flutter test --coverage
    # - uses: romeovs/lcov-reporter-action@v0.2.16
    #   with:
    #     lcov-file: ./packages/vector_graphics_compiler/coverage/lcov.info
    #     github-token: ${{ secrets.GITHUB_TOKEN }}

  test_windows:
    runs-on: windows-2022
    defaults:
      run:
        working-directory: packages/vector_graphics_compiler
    steps:
    - uses: actions/checkout@v4
    - uses: subosito/flutter-action@v2
      with:
        cache: true
    - run: flutter test

  test_mac_x86:
    runs-on: macos-13
    defaults:
      run:
        working-directory: packages/vector_graphics_compiler
    steps:
    - uses: actions/checkout@v4
    - uses: subosito/flutter-action@v2
      with:
        cache: true
    - run: flutter test

  test_mac_m1:
    runs-on: macos-14
    defaults:
      run:
        working-directory: packages/vector_graphics_compiler
    steps:
    - uses: actions/checkout@v4
    - uses: subosito/flutter-action@v2
      with:
        cache: true
    - run: flutter test
